apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: checkpoint-mdm-policy
  description: Check Point MDM policy deployment

spec:
  type: service
  owner: user:guest
  lifecycle: development
