apiVersion: backstage.io/v1alpha1
kind: Component

metadata:
  name: checkpoint-mdm-policy
  description: Check Point MDM policy deployment
  tags:
    - checkpoint
    - python
    - automation
  links:
    - url: https://github.com/mcevansw/checkpoint-mdm-policy
      title: GitHub Repository

spec:
  type: service
  owner: guests
  lifecycle: development
